version: '2'

services:
  cmdicdn:
    image: registry.diginfra.net/tsd/huc-generic-editor:1.3-RC5-alpha
    container_name: cmdicdn
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.alpha-cmdicdn.entrypoints=http"
      - "traefik.http.routers.alpha-cmdicdn.rule=Host(`alpha-cmdicdn.sd.di.huc.knaw.nl`)"
    networks:
      - traefik-public

networks:
  traefik-public:
    external: true